library(TTR)
library(forecast)
#CRM <- read.xlsx("PublicationReports2017_1a.xlsx", sheetName = "Assault", rowIndex = 1:16, colIndex = 12:153, header = TRUE )
CRM <- read.csv("C:/Users/Anant Joshi/Documents/AssaultDM.csv", header = TRUE)
TSvector <- as.numeric(CRM[35,4:16])
CRM[35,4:16]
CRMtimeseries <- ts(TSvector, frequency = 1, start = 2003, end = 2015)
plot.ts(CRMtimeseries)
#CRMtimeseriesSMA <- SMA(CRMtimeseries)
#plot.ts(CRMtimeseriesSMA)
#CRMforecast <- HoltWinters(CRMtimeseries, beta = FALSE, gamma = FALSE)
#plot(CRMforecast)
#CRMforecast2 <- forecast(CRMforecast, h=5)
#plot(CRMforecast2)
#acf(CRMforecast2$residuals, na.action = na.pass, lag.max = 20)
#pacf(CRMforecast2$residuals, na.action = na.pass, lag.max = 20)
#CRMdiff <- diff(CRMtimeseries, differences = 1)
auto.arima(CRMtimeseries)
acf(CRMtimeseries, lag.max = 20)
pacf(CRMtimeseries, lag.max = 20)
CRMarimaseries <- arima(CRMtimeseries, order=c(3,0,0))
CRMforecastARIMA <- forecast(CRMarimaseries, h = 10)
plot(CRMforecastARIMA)
