library(TTR)
library(highcharter)
library(forecast)
#CRM <- read.xlsx("PublicationReports2017_1a.xlsx", sheetName = "Assault", rowIndex = 1:16, colIndex = 12:153, header = TRUE )
CRM <- read.csv("C:/Users/Anant Joshi/Documents/CrimeData/data/Assault.csv", header = TRUE)
CRM$Region <- NULL
CRM$Sub.region <- NULL
TSvector <- (CRM[35,15:27])
hchart1 <- hchart(TSvector, type = "line", x = )
plot(hchart1)
TSvector <- as.numeric(as.vector(t(TSvector)[1,]))
hchart1 <- hchart(TSvector, type = "line")
plot(hchart1)
CRM[35, 15:27]
TSvector
CRMtimeseries <- ts(TSvector, frequency = 1, start = 2003, end = 2015)
plot.ts(CRMtimeseries)

CRMtimeseriesSMA <- SMA(CRMtimeseries, n=4)
plot.ts(CRMtimeseriesSMA)

CRMtimeseries <- diff(CRMtimeseries, n=1)
plot.ts(CRMtimeseries)
#plot.ts(CRMtimeseriesSMA)
#CRMforecast <- HoltWinters(CRMtimeseries, beta = FALSE, gamma = FALSE)
#plot(CRMforecast)
# CRMforecast2 <- forecast(CRMforecast, h=5)
# plot(CRMforecast2)
#acf(CRMforecast2$residuals, na.action = na.pass, lag.max = 20)
#pacf(CRMforecast2$residuals, na.action = na.pass, lag.max = 20)
#CRMdiff <- diff(CRMtimeseries, differences = 1)
auto.arima(CRMtimeseries)
acf(CRMtimeseries, lag.max = 20)
pacf(CRMtimeseries, lag.max = 20)
CRMarimaseries <- arima(CRMtimeseries, order=c(0,1,0))
CRMforecastARIMA <- forecast(CRMarimaseries, h = 5)
plot.ts(CRMarimaseries$residuals)
plotForecastErrors(CRMarimaseries$residuals) 
plot(CRMforecastARIMA)
